# Generated by Django 4.1.2 on 2022-12-21 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("album_name", models.CharField(max_length=255)),
                ("album_price", models.IntegerField()),
                ("album_producer", models.CharField(max_length=255)),
                ("release_year", models.CharField(max_length=255, null=True)),
                ("cover", models.CharField(max_length=255, null=True)),
                ("type", models.IntegerField()),
                ("source", models.CharField(max_length=255, null=True)),
                ("sales_volume", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Musician",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("musician_name", models.CharField(max_length=255)),
                ("photo", models.CharField(max_length=255, null=True)),
                ("nationality", models.TextField()),
                ("location", models.TextField(null=True)),
                ("theme", models.TextField(null=True)),
                ("found_year", models.TextField(null=True)),
                ("info", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("user_name", models.CharField(max_length=255)),
                ("avatar", models.CharField(max_length=255, null=True)),
                ("password", models.CharField(max_length=255)),
                ("user_type", models.IntegerField()),
                ("bio", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_name", models.CharField(max_length=255)),
                ("tag_type", models.CharField(max_length=255)),
                ("popularity", models.IntegerField()),
            ],
            options={"unique_together": {("tag_name", "tag_type")},},
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Archipelago_backend.album",
                    ),
                ),
                (
                    "consumer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Archipelago_backend.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MusicianTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "musician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Archipelago_backend.musician",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Archipelago_backend.tag",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MusicianMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("member_name", models.CharField(max_length=255)),
                ("active_year", models.CharField(max_length=255, null=True)),
                ("birthday", models.CharField(max_length=255, null=True)),
                ("role", models.CharField(max_length=255, null=True)),
                (
                    "musician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Archipelago_backend.musician",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="musician",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Archipelago_backend.user",
            ),
        ),
        migrations.CreateModel(
            name="AlbumTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Archipelago_backend.album",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Archipelago_backend.tag",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="album",
            name="musician",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Archipelago_backend.musician",
            ),
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("song_name", models.CharField(max_length=255)),
                ("song_last", models.IntegerField()),
                ("resource", models.CharField(max_length=255)),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Archipelago_backend.album",
                    ),
                ),
            ],
            options={"unique_together": {("song_name", "album")},},
        ),
    ]
