// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AlbumChange: typeof import('./components/Album/AlbumChange.vue')['default']
    AlbumTable: typeof import('./components/Album/AlbumTable.vue')['default']
    AudienceIndex: typeof import('./components/AudienceIndex.vue')['default']
    AudienceSide: typeof import('./components/Admin/AudienceSide.vue')['default']
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    BaseSide: typeof import('./components/layouts/BaseSide.vue')['default']
    ChangeNN: typeof import('./components/Settings/ChangeNN.vue')['default']
    ChangePWD: typeof import('./components/Settings/ChangePWD.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Index: typeof import('./components/Index.vue')['default']
    Login: typeof import('./components/Admin/Login.vue')['default']
    MusicianChange: typeof import('./components/Musician/MusicianChange.vue')['default']
    MusicianIndex: typeof import('./components/MusicianIndex.vue')['default']
    MusicianProfile: typeof import('./components/Musician/MusicianProfile.vue')['default']
    MusicianSide: typeof import('./components/Admin/MusicianSide.vue')['default']
    Register: typeof import('./components/Admin/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingChange: typeof import('./components/Settings/SettingChange.vue')['default']
    SettingPage: typeof import('./components/Settings/SettingPage.vue')['default']
  }
}

export {}
