// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AlbumTable: typeof import('./components/Album/AlbumTable.vue')['default']
    AlbumTableCard: typeof import('./components/Album/AlbumTableCard.vue')['default']
    AudienceIndex: typeof import('./components/layouts/AudienceIndex.vue')['default']
    AudienceSide: typeof import('./components/layouts/AudienceSide.vue')['default']
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    BaseSide: typeof import('./components/layouts/BaseSide.vue')['default']
    HelloWorld: typeof import('./components/layouts/HelloWorld.vue')['default']
    Index: typeof import('./components/layouts/Index.vue')['default']
    LoginNRegister: typeof import('./components/layouts/LoginNRegister.vue')['default']
    MusicianIndex: typeof import('./components/layouts/MusicianIndex.vue')['default']
    MusicianProfile: typeof import('./components/Musician/MusicianProfile.vue')['default']
    MusicianProfileCard: typeof import('./components/Musician/MusicianProfileCard.vue')['default']
    MusicianSide: typeof import('./components/layouts/MusicianSide.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingCard: typeof import('./components/Settings/SettingCard.vue')['default']
    SettingPage: typeof import('./components/Settings/SettingPage.vue')['default']
    UserHeader: typeof import('./components/layouts/UserHeader.vue')['default']
  }
}

export {}
